version: "3.8"

services:
  app:
    image: php:8.1-fpm
    container_name: app
    build: ./fpm
    environment:
      - PHP_IDE_CONFIG=serverName=application
    volumes:
      - ./app:/var/www/html
    networks:
      - app-net

  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - ${APP_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/var/www/html
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
